apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/deployment.yaml
- ../base/service.yaml
patchesStrategicMerge:
- deployment.yaml
- service.yaml 

replicas:
  - name: vote
    count: 3 

images:
- name: schoolofdevops/vote
  newTag: v8 # {"$imagepolicy": "flux-system:vote:tag"}

namespace: instavote
